events {
    worker_connections 1024;
}

http {

    upstream auth_service {
        server host.docker.internal:5001;
    }

    upstream website_service {
        server host.docker.internal:5002;
    }

    server {
        listen 80;
        server_name localhost;

        # Auth Service
        location /api/auth/ {
            proxy_pass http://auth_service;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Website Service
        location /api/websites/ {
            proxy_pass http://website_service;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}