events {
    worker_connections 1024;
}

http {

   

    server {

        listen 80;

        server_name localhost;


        location / {

            return 200 "MonitorX API Gateway Running";

            add_header Content-Type text/plain;
        }


        error_page 502 /502.html;

        location = /502.html {

            return 502 '{"error":{"status_code":502,"status":"Bad Gateway"}}';

            default_type application/json;
        }

    }

}